### ISSUE TITLE
moreButtons can't be empty

### ISSUE THREAD

**Issue by misskter** [ketanchoyal/extended_navbar_scaffold#5]
when i use this plugin, I try to set morebuttons to null, but I get an exception
The method '[]' was called on null.
Receiver: null
Tried calling: [](0)

**Comment by ketanchoyal** [comment]
You can't put whole morebuttons as null you have to put it as [null, null, null, null....] (nine times as it has nine buttons). (I know it's lame, I'm soon going to make changes)
